apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  template:
    spec:
    replicas: 3
      containers:
      - name: demo
        env:
        - name: ENVIRONMENT
          value: e2e
