apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -hello-prod

patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: invaleed/argo-hello
  newTag: ac6bbe731cd9824ea7b2cdb5ec5b548d7960c74b
resources:
- ../base
